# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:

- task: NuGetCommand@2
  inputs:
    restoreSolution: '*.sln'
    
- task: MSBuild@1
  inputs:
    solution: '*.sln' 

- task: CopyFiles@2
  inputs:
    sourceFolder: ParameterSettingsDemo
    targetFolder: '$(Build.ArtifactStagingDirectory)'    

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'embersilk-published'
